name: app_disco_teca
description: "DiscoTeca: un'app per gestire la tua libreria dei dischi."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.2.2+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  intl:
  image:
  image_picker:
  cupertino_icons: ^1.0.2
  flutter_bloc:
  dartz:
  dio:
  logger:
  get_it:
  flutter_secure_storage:
  google_fonts: ^5.1.0
  open_filex:
  package_info_plus:
  google_sign_in:
  google_sign_in_web:
  cached_network_image:
  introduction_screen:
  image_cropper:

  # Firebase
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.14
  firebase_remote_config: ^4.3.13
  firebase_remote_config_web: ^1.4.21
  firebase_core_web: ^2.11.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "icons/logo.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/gifs/
    - assets/icons/
